import type { CollectedDocs, DocSlot } from "./project-docs.js";

export const TASK_GENERATE_SCHEMA_VERSION = 1;

export const REQUIRED_TASK_SECTIONS: readonly string[] = [
  "Status",
  "MVP Phase",
  "Goal",
  "Background",
  "Scope",
  "Out of Scope",
  "Acceptance Criteria",
  "Files to Inspect First",
  "Expected Files to Change",
  "Risks",
  "Test Plan",
  "Rollback Plan",
  "Git Context",
  "Notion Page",
  "Implementation Plan",
  "Result",
  "Test Result",
  "Review Notes",
];

/**
 * Convert an arbitrary string to a TASK-filename slug.
 * - lowercase
 * - ASCII-only (non-ASCII letters dropped)
 * - non-alphanum collapsed to `-`
 * - leading/trailing `-` removed, repeated `-` compressed
 * - empty result → `task`
 */
export function slugify(input: string, fallback = "task"): string {
  const cleaned = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return cleaned.length > 0 ? cleaned : fallback;
}

export interface BuildTaskGeneratePromptInputs {
  cwd: string;
  vibeopsVersion: string;
  generatedAt: string;
  /** advisory next TASK id reserved for the Planner Agent (e.g. "TASK-013") */
  nextTaskId: string;
  /** advisory recommended count (defaults to 8) */
  count: number;
  /** optional MVP phase filter (e.g. "MVP 4") */
  phase?: string;
  /** absolute path the prompt will be written to */
  outputPath: string;
  /** relative path of outputPath */
  outputRelative: string;
  /** docs collected from disk */
  docs: CollectedDocs;
  /** countCap exceeded warning (true if count > soft cap) */
  countWarning: boolean;
}

function header(inputs: BuildTaskGeneratePromptInputs): string {
  const lines: string[] = [];
  lines.push("# VibeOps Task-Generation Prompt — Cursor Planner Agent");
  lines.push("");
  lines.push(
    "> 이 파일은 `vibeops task generate`가 만들었다. **Cursor**에서 새 채팅을 열고 이 파일의 전체 내용을 그대로 붙여 넣어라. VibeOps는 LLM·Cursor CLI·Notion·GitHub API를 직접 호출하지 않는다 — 이 프롬프트를 받은 **Planner Agent**가 `docs/tasks/TASK-*.md` 파일을 만든다.",
  );
  lines.push("");
  lines.push(`- VibeOps version: ${inputs.vibeopsVersion}`);
  lines.push(`- Generated: ${inputs.generatedAt}`);
  lines.push(`- Generated by: \`vibeops task generate\``);
  lines.push(`- Prompt location: \`${inputs.outputRelative}\``);
  lines.push(`- Schema version: ${TASK_GENERATE_SCHEMA_VERSION}`);
  lines.push("");
  return lines.join("\n");
}

function role(): string {
  return `## Role: Planner Agent

\`.vibeops/agents/planner.md\`의 정의를 따른다(설치돼 있다면). 너는 **애플리케이션 코드를 작성하지 않는다**. 너는 \`docs/tasks/TASK-NNN-slug.md\` 파일들을 만든다. 각 TASK는 한 명의 Builder Agent가 한 번의 Cursor 작업으로 끝낼 수 있을 만큼 작아야 한다.`;
}

function hardRules(): string {
  return `## Hard rules (지키지 않으면 작업 실패)

- 애플리케이션 코드(\`src/**\`, \`lib/**\`, \`app/**\`, 테스트, 빌드 스크립트 등)를 절대 만들지 마라. 이번 단계의 결과물은 \`docs/tasks/TASK-NNN-slug.md\`로 한정한다.
- VibeOps 자체 설정(\`.vibeops/\`, \`.vibeops.json\`, \`templates/\`)은 건드리지 마라.
- LLM API / Cursor CLI / Notion API / GitHub API를 직접 호출하지 마라. 너는 마크다운만 만든다.
- 진실 공급원 규칙:
  - **\`docs/tasks/*.md\` = AI execution source of truth** (Builder/Reviewer/Tester agent는 이 파일만 읽고 작업).
  - **\`docs/project/*.md\` = 설계·현재 상태 기준** (Planner가 본 라운드의 입력으로 쓰는 곳).
  - **Git commits/branches = 변경 이력**.
  - **Notion = human dashboard** (요약·상태·우선순위·docs 경로만 노출; 실행 정보는 들어가지 않음).
  - 채팅 기억은 신뢰하지 마라.
- 한 TASK는 한 가지에 집중하라. TASK 간 의존성은 본문에 명시하라(예: "TASK-014 depends on TASK-013").
- 가정(Assumption)은 절대 숨기지 마라. 응답 끝의 "Assumptions" 섹션에 기록하라.`;
}

function inventoryRow(slot: DocSlot): string {
  const flag = slot.content === null ? "·" : "✓";
  const note = slot.content === null ? " _(missing)_" : "";
  const primaryTag = slot.primary ? " **(primary)**" : "";
  return `- [${flag}] \`${slot.relativePath}\` — ${slot.label}${primaryTag}${note}`;
}

function inventory(docs: CollectedDocs): string {
  const lines: string[] = ["## Input documents (이 라운드에서 참고)"];
  lines.push("");
  if (docs.from) lines.push(inventoryRow(docs.from));
  for (const slot of docs.slots) lines.push(inventoryRow(slot));
  lines.push(inventoryRow(docs.brief));
  lines.push("");
  lines.push("> `[✓]` = 디스크에서 읽을 수 있었던 파일. `[·]` = 누락 또는 빈 파일이라 본 프롬프트에 내용이 들어가지 않은 슬롯. 누락된 항목은 무리해서 추론하지 말고 \"Assumptions\"에 기록하라.");
  return lines.join("\n");
}

function objective(inputs: BuildTaskGeneratePromptInputs): string {
  const lines: string[] = ["## 목표"];
  lines.push("");
  lines.push(
    `위 입력을 읽고 **${inputs.count}개 내외**의 새 TASK 파일을 만든다. 첫 번째 TASK 번호는 \`${inputs.nextTaskId}\`로 시작한다(기존 \`docs/tasks/TASK-*.md\`의 가장 큰 번호 다음). 같은 번호가 이미 있다면 건너뛰고 다음 번호를 쓴다.`,
  );
  if (typeof inputs.phase === "string" && inputs.phase.length > 0) {
    lines.push("");
    lines.push(
      `- **MVP Phase 필터**: 이 라운드에서는 \`${inputs.phase}\` 에 속하는 TASK만 만든다. 다른 phase의 작업이 보이더라도 본 라운드에는 포함시키지 마라.`,
    );
  }
  if (inputs.countWarning) {
    lines.push("");
    lines.push(
      `- ⚠️ 권장 개수 ${inputs.count}는 한 번에 다루기 큰 편이다. 각 TASK가 정말 한 번의 Cursor 작업으로 끝나는지 확인하고, 너무 모호하면 적은 수로 줄여 응답해도 좋다.`,
    );
  }
  lines.push("");
  lines.push("각 TASK는 다음 원칙을 만족해야 한다:");
  lines.push("");
  lines.push("- **작고 검증 가능한 단위**. 한 명의 Builder가 한 번의 Cursor 작업으로 끝낼 수 있어야 한다.");
  lines.push("- **자기 완결**. TASK 본문만 읽고도 어떤 파일을 만들지 / Acceptance 가 무엇인지 알 수 있어야 한다.");
  lines.push("- **다른 TASK 의존**이 있으면 Background에서 \"depends on TASK-NNN\"로 명시한다.");
  return lines.join("\n");
}

function fileFormat(inputs: BuildTaskGeneratePromptInputs): string {
  const sections = REQUIRED_TASK_SECTIONS.map((s) => `   - \`## ${s}\``).join("\n");
  return `## 출력 형식

응답은 다음 순서를 정확히 지킨다.

1. **Plan summary** — 5 ~ 8 bullet. 입력 문서에서 도출한 우선순위 / 분해 방침.
2. **TASK 파일들** — 각각 fenced code block 하나에 한 파일. 각 block 첫 줄은 \`<!-- file: docs/tasks/TASK-NNN-slug.md -->\` (HTML comment) 로 시작한다. 번호는 \`${inputs.nextTaskId}\`부터 순차 증가. \`slug\`는 lowercase / ASCII / \`-\` 구분(예: \`docs-and-readme\`).
3. **Changed file list** — 위에서 만든 모든 \`docs/tasks/TASK-NNN-*.md\` 경로 목록.
4. **Generated TASK summary** — \`TASK-NNN · title · MVP Phase · 한 줄 요약\` 표 또는 bullet 목록.
5. **Assumptions** — 사람이 다시 확인해야 할 가정(없으면 \`(none)\`).

### 각 TASK 파일이 반드시 포함해야 할 섹션 (이 순서, 같은 헤딩 텍스트)

각 TASK 마크다운은 \`# ${inputs.nextTaskId} · <one-line title>\`로 시작하고, 그 아래에 다음 \`##\` 섹션을 **모두** 가진다.

${sections}

추가 규칙:

- \`## Status\` 의 본문은 \`planned\` 한 단어.
- \`## MVP Phase\` 의 본문은 \`${typeof inputs.phase === "string" && inputs.phase.length > 0 ? inputs.phase : "MVP <n> · <phase name>"}\` 형식. 모르면 \`(미정)\`.
- \`## Git Context\` 의 본문은 \`(시작 시 \\\`vibeops task start TASK-NNN\\\`이 채움)\`.
- \`## Notion Page\` 의 본문은 \`(MVP 4 / TASK-011 \\\`vibeops notion sync\\\`가 채움)\`.
- \`## Result\` / \`## Test Result\` / \`## Review Notes\` 의 본문은 \`(미수행)\`.`;
}

function workflowReminders(): string {
  return `## 운영 규칙 (다시 강조)

- **VibeOps의 진실 공급원은 \`docs/tasks/\` + \`docs/project/\` + Git이다.** Notion은 사람을 위한 대시보드일 뿐 AI 실행에는 쓰지 않는다.
- TASK는 만든 즉시 \`vibeops task start TASK-NNN\`로 라이프사이클에 진입할 수 있어야 한다. 따라서 슬러그는 깔끔하게, 번호는 충돌 없이.
- 코드는 절대 만들지 마라. 다른 라운드의 Builder Agent가 만든다.
- 모호한 부분은 \`Risks\` 와 \`Assumptions\`에 분리해서 기록하라.`;
}

function fileSection(doc: DocSlot, fenceLang = ""): string {
  if (doc.content === null) {
    return `### \`${doc.relativePath}\` _(missing)_\n\n_(file not found — Planner Agent는 이 문서가 없다는 사실을 가정으로 기록해야 한다.)_`;
  }
  const fence = "```";
  const lang = fenceLang.length > 0 ? fenceLang : "markdown";
  return `### \`${doc.relativePath}\`\n\n${fence}${lang}\n${doc.content.trimEnd()}\n${fence}`;
}

function inlineInputs(docs: CollectedDocs): string {
  const parts: string[] = ["## 입력 문서 (inline)"];
  parts.push("");
  parts.push(
    "아래 코드 블록들은 본 프롬프트를 만든 시점의 디스크 스냅샷이다. Cursor 안에서 다른 컨텍스트 파일을 더 열 수 있지만, **반드시 아래 내용에서 시작**한다.",
  );
  parts.push("");
  if (docs.from) parts.push(fileSection(docs.from));
  for (const slot of docs.slots) parts.push(fileSection(slot));
  parts.push(fileSection(docs.brief));
  return parts.join("\n\n");
}

function footer(): string {
  return `---

이제 위 규칙을 모두 지켜 응답을 작성하라. 응답이 끝나면 사람이 \`git diff\`로 만들어진 \`docs/tasks/TASK-*.md\`를 검토한 뒤 커밋한다. 커밋 후 첫 번째 TASK부터 \`vibeops task start TASK-NNN\`로 라이프사이클을 시작한다.`;
}

export function buildTaskGeneratePrompt(inputs: BuildTaskGeneratePromptInputs): string {
  return [
    header(inputs),
    role(),
    hardRules(),
    inventory(inputs.docs),
    objective(inputs),
    fileFormat(inputs),
    workflowReminders(),
    inlineInputs(inputs.docs),
    footer(),
  ].join("\n\n");
}
