import { join } from "node:path";

import { VERSION } from "../version.js";

export function taskBuildPromptRel(taskId: string): string {
  const slug = taskId.toLowerCase().replace(/[^a-z0-9-]+/g, "-");
  return `.vibeops/generated/task-build-${slug}.md`;
}

export function buildTaskBuildPrompt(params: {
  readonly projectName: string;
  readonly taskId: string;
  readonly taskRelativePath: string;
}): string {
  return `# Build ${params.taskId} — ${params.projectName}

You are the **implementer** in Cursor for this repository. Deliver everything in the TASK file below. VibeOps owns Git/docs rails; **you** own code and verification.

## Source of truth (read first)

1. \`AGENTS.md\` and \`.cursor/rules/\`
2. \`docs/project/05-current-state.md\` (or \`03-current-state.md\` if present)
3. \`docs/project/02-mvp-scope.md\`, \`03-architecture.md\`, \`04-tech-stack.md\`, \`06-decisions.md\`
4. TASK file: \`${params.taskRelativePath}\` — work **only** inside Scope / Acceptance Criteria

## How to work

- Implement **only** \`${params.taskId}\`. Do not start other TASK ids unless the human asks.
- **Search** the repo before adding files; reuse existing patterns.
- Fill **Result** and **Test Result** in the TASK file with facts (paths, commands, outcomes).
- No \`git push\` or merge — the human runs \`vibeops done ${params.taskId}\` when ready.

## Definition of done

1. Every **Acceptance Criteria** item in \`${params.taskRelativePath}\` is met.
2. **Result** and **Test Result** are filled (not placeholders).
3. Working tree is ready to commit on the task branch if needed.

---

*Generated by \`vibeops task add\` (VibeOps ${VERSION}).*
`;
}

export function taskBuildPromptAbs(cwd: string, taskId: string): string {
  return join(cwd, taskBuildPromptRel(taskId));
}
