import type { CollectedDocs, DocSlot } from "./project-docs.js";

export const TASK_GENERATE_SCHEMA_VERSION = 1;

export const REQUIRED_TASK_SECTIONS: readonly string[] = [
  "Status",
  "MVP Phase",
  "Goal",
  "Background",
  "Scope",
  "Out of Scope",
  "Acceptance Criteria",
  "Files to Inspect First",
  "Expected Files to Change",
  "Risks",
  "Test Plan",
  "Rollback Plan",
  "Git Context",
  "Notion Page",
  "Implementation Plan",
  "Result",
  "Test Result",
  "Review Notes",
];

/**
 * Convert an arbitrary string to a TASK-filename slug.
 * - lowercase
 * - ASCII-only (non-ASCII letters dropped)
 * - non-alphanum collapsed to `-`
 * - leading/trailing `-` removed, repeated `-` compressed
 * - empty result → `task`
 */
export function slugify(input: string, fallback = "task"): string {
  const cleaned = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return cleaned.length > 0 ? cleaned : fallback;
}

export interface BuildTaskGeneratePromptInputs {
  cwd: string;
  vibeopsVersion: string;
  generatedAt: string;
  /** advisory next TASK id reserved for the Planner Agent (e.g. "TASK-013") */
  nextTaskId: string;
  /** advisory recommended count (defaults to 8) */
  count: number;
  /** optional MVP phase filter (e.g. "MVP 4") */
  phase?: string;
  /** absolute path the prompt will be written to */
  outputPath: string;
  /** relative path of outputPath */
  outputRelative: string;
  /** docs collected from disk */
  docs: CollectedDocs;
  /** countCap exceeded warning (true if count > soft cap) */
  countWarning: boolean;
}

function header(inputs: BuildTaskGeneratePromptInputs): string {
  const lines: string[] = [];
  lines.push("# VibeOps Task-Generation Prompt — Cursor Planner Agent");
  lines.push("");
  lines.push(
    "> This file was produced by `vibeops task generate`. Open a new chat in **Cursor** and paste the full contents of this file. VibeOps does not call LLM, Cursor CLI, Notion, or GitHub APIs directly — the **Planner Agent** receiving this prompt creates the `docs/tasks/TASK-*.md` files.",
  );
  lines.push("");
  lines.push(`- VibeOps version: ${inputs.vibeopsVersion}`);
  lines.push(`- Generated: ${inputs.generatedAt}`);
  lines.push(`- Generated by: \`vibeops task generate\``);
  lines.push(`- Prompt location: \`${inputs.outputRelative}\``);
  lines.push(`- Schema version: ${TASK_GENERATE_SCHEMA_VERSION}`);
  lines.push("");
  return lines.join("\n");
}

function role(): string {
  return `## Role: Planner Agent

Follow the definition in \`.vibeops/agents/planner.md\` if it is installed. You **do not write application code**. You produce \`docs/tasks/TASK-NNN-slug.md\` files. Each TASK must be small enough for a single Builder Agent to finish in one Cursor session.`;
}

function hardRules(): string {
  return `## Hard rules (failure if violated)

- Never produce application code (\`src/**\`, \`lib/**\`, \`app/**\`, tests, build scripts, etc.). The deliverable for this round is \`docs/tasks/TASK-NNN-slug.md\` files only.
- Do not touch VibeOps' own config (\`.vibeops/\`, \`.vibeops.json\`, \`templates/\`).
- Never call LLM APIs, Cursor CLI, Notion APIs, or GitHub APIs directly. You only produce markdown.
- Source-of-truth rules:
  - **\`docs/tasks/*.md\` = AI execution source of truth** (Builder/Reviewer/Tester agents only read these files).
  - **\`docs/project/*.md\` = design + current-state baseline** (the input the Planner reads for this round).
  - **Git commits/branches = change history**.
  - **Notion = human dashboard** (exposes summary / status / priority / docs path only — never execution details).
  - Do not trust chat memory.
- One TASK, one focus. Surface inter-TASK dependencies in the body (e.g. "TASK-014 depends on TASK-013").
- Never hide assumptions. Record them in the closing "Assumptions" section of the response.`;
}

function inventoryRow(slot: DocSlot): string {
  const flag = slot.content === null ? "·" : "✓";
  const note = slot.content === null ? " _(missing)_" : "";
  const primaryTag = slot.primary ? " **(primary)**" : "";
  return `- [${flag}] \`${slot.relativePath}\` — ${slot.label}${primaryTag}${note}`;
}

function inventory(docs: CollectedDocs): string {
  const lines: string[] = ["## Input documents (for this round)"];
  lines.push("");
  if (docs.from) lines.push(inventoryRow(docs.from));
  for (const slot of docs.slots) lines.push(inventoryRow(slot));
  lines.push(inventoryRow(docs.brief));
  lines.push("");
  lines.push("> `[✓]` = file read from disk. `[·]` = missing or empty slot — its content is not inlined below. Do not over-guess for missing slots; record them in \"Assumptions\".");
  return lines.join("\n");
}

function objective(inputs: BuildTaskGeneratePromptInputs): string {
  const lines: string[] = ["## Objective"];
  lines.push("");
  lines.push(
    `Read the inputs above and produce roughly **${inputs.count} new TASK files**. The first TASK number is \`${inputs.nextTaskId}\` (the next number after the highest existing \`docs/tasks/TASK-*.md\`). Skip any number that already exists on disk.`,
  );
  if (typeof inputs.phase === "string" && inputs.phase.length > 0) {
    lines.push("");
    lines.push(
      `- **Phase filter**: this round only produces TASKs whose phase is \`${inputs.phase}\`. Even if you see work for other phases, leave it for a separate round.`,
    );
  }
  if (inputs.countWarning) {
    lines.push("");
    lines.push(
      `- ⚠️ A recommended count of ${inputs.count} is on the high side. Make sure each TASK really does fit a single Cursor session, and lower the count if anything is vague.`,
    );
  }
  lines.push("");
  lines.push("Each TASK must satisfy:");
  lines.push("");
  lines.push("- **Small, verifiable scope**. One Builder finishes it in one Cursor session.");
  lines.push("- **Self-contained**. A reader can determine the files to change and the Acceptance Criteria from the TASK body alone.");
  lines.push("- **Explicit dependencies**. If TASK depends on another, write \"depends on TASK-NNN\" in Background.");
  return lines.join("\n");
}

function fileFormat(inputs: BuildTaskGeneratePromptInputs): string {
  const sections = REQUIRED_TASK_SECTIONS.map((s) => `   - \`## ${s}\``).join("\n");
  return `## Output format

Produce the response in this exact order:

1. **Plan summary** — 5 to 8 bullets. Priorities / decomposition derived from the inputs.
2. **TASK files** — each in its own fenced code block. The first line of each block must be \`<!-- file: docs/tasks/TASK-NNN-slug.md -->\` (an HTML comment) marking the path. Numbers increase sequentially from \`${inputs.nextTaskId}\`. Slugs are lowercase / ASCII / hyphen-separated (e.g. \`docs-and-readme\`).
3. **Changed file list** — every \`docs/tasks/TASK-NNN-*.md\` path produced above.
4. **Generated TASK summary** — table or bullet list: \`TASK-NNN · title · MVP Phase · one-line summary\`.
5. **Assumptions** — items a human needs to reconfirm (use \`(none)\` if there are none).

### Required sections per TASK file (same order, same heading text)

Each TASK markdown begins with \`# ${inputs.nextTaskId} · <one-line title>\` and includes **all** of the following \`##\` sections:

${sections}

Additional rules:

- The body of \`## Status\` is the single word \`planned\`.
- The body of \`## MVP Phase\` follows \`${typeof inputs.phase === "string" && inputs.phase.length > 0 ? inputs.phase : "MVP <n> · <phase name>"}\` (or \`(unassigned)\` when unknown).
- The body of \`## Git Context\` is \`(populated by \\\`vibeops task start TASK-NNN\\\`)\`.
- The body of \`## Notion Page\` is \`(populated by \\\`vibeops notion sync\\\`)\`.
- The body of \`## Result\` / \`## Test Result\` / \`## Review Notes\` is \`(not yet)\`.`;
}

function workflowReminders(): string {
  return `## Workflow reminders

- **VibeOps source of truth = \`docs/tasks/\` + \`docs/project/\` + Git.** Notion is a human dashboard and is never used for AI execution.
- Once produced, each TASK must be ready for \`vibeops task start TASK-NNN\`. Keep slugs clean and numbers conflict-free.
- Never produce application code — a separate Builder Agent does that in a different round.
- Separate ambiguity into \`Risks\` (known unknowns) and \`Assumptions\` (need confirmation).`;
}

function fileSection(doc: DocSlot, fenceLang = ""): string {
  if (doc.content === null) {
    return `### \`${doc.relativePath}\` _(missing)_\n\n_(file not found — the Planner Agent must record this in Assumptions.)_`;
  }
  const fence = "```";
  const lang = fenceLang.length > 0 ? fenceLang : "markdown";
  return `### \`${doc.relativePath}\`\n\n${fence}${lang}\n${doc.content.trimEnd()}\n${fence}`;
}

function inlineInputs(docs: CollectedDocs): string {
  const parts: string[] = ["## Inline inputs"];
  parts.push("");
  parts.push(
    "The code blocks below are the on-disk snapshot at prompt generation time. Cursor may open additional context, but **start from these**.",
  );
  parts.push("");
  if (docs.from) parts.push(fileSection(docs.from));
  for (const slot of docs.slots) parts.push(fileSection(slot));
  parts.push(fileSection(docs.brief));
  return parts.join("\n\n");
}

function footer(): string {
  return `---

Apply the rules above and produce the response. After you respond, a human reviews the generated \`docs/tasks/TASK-*.md\` files via \`git diff\` and commits them, then starts the first TASK with \`vibeops task start TASK-NNN\`.`;
}

export function buildTaskGeneratePrompt(inputs: BuildTaskGeneratePromptInputs): string {
  return [
    header(inputs),
    role(),
    hardRules(),
    inventory(inputs.docs),
    objective(inputs),
    fileFormat(inputs),
    workflowReminders(),
    inlineInputs(inputs.docs),
    footer(),
  ].join("\n\n");
}
